FROM debian
EXPOSE 5000
WORKDIR /app

RUN apt-get update \
 && apt-get -y install --allow-unauthenticated libgdiplus libc6-dev libx11-dev xvfb libssl-dev \
 && rm -rf /var/lib/apt/lists/*
 
ENV DISPLAY :10
CMD nohup /usr/bin/Xvfb :10 -ac >> /dev/null 2>&1 & \
 && /app/RoadFlow.Mvc
